### ISSUE TITLE
OONI Run v2 UX

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#1401] opened 2023-08-09 13:30 UTC
This involves iterating on mockups for form editor and OONI Run v2 in apps. It also will involve doing a usability study.

**Comment by jbonisteel** [comment] 2023-11-15 13:57
I am going to close this issue, it looks like actually a duplicate of run#130 and the various issues spun up for tracking mobile UI changes.

**Closed by jbonisteel** 2023-11-15 13:57 UTC
Labels: epic, funder/mozilla2023
