### ISSUE TITLE
ooni.org 

### ISSUE THREAD

**Issue by molafir** [ooni/ooni.org#888] opened 2021-05-22 11:21 UTC
ooni.org
filter in iran hiweb.ir operator mobile
ooni app not work for test

**Comment by hellais** [comment] 2021-05-25 14:24
Thanks for reporting this issue. We are aware of the fact that there are some issue with using OONI Probe in Iran and have been working on adding proxy support to the app, which is going to be shipping in the upcoming 3.0.0 mobile app release.

This issue is a duplicate of: https://github.com/ooni/probe/issues/1324

**Closed by hellais** 2021-05-25 14:24 UTC
