### ISSUE TITLE
Create a Social Media Censorship Alert System

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#1300] opened 2022-11-18 13:22 UTC
Major social media platforms (such as Facebook, WhatsApp, and Twitter) are frequently blocked around the world during political events (such as elections or large-scale protests). Over the years, OONI data has demonstrated the blocking of social media platforms in numerous countries (such as Uganda, Mali, Benin, Togo, Burundi, Tanzania and Zambia) during elections. OONI data has also shown the blocking of social media platforms during Cuba’s July 2021 anti-government protests, Zimbabwe’s 2019 fuel protests, and Iran’s 2017-2018 anti-government protests (among many other cases worldwide). Following the February 2021 military coup in Myanmar, ISPs in the country started blocking access to social media platforms. Following the February 2022 invasion of Ukraine, Russia started blocking access to Facebook and Twitter. 

To enable human rights defenders to rapidly respond to social media blocks, we aim to create a **Social Media Censorship Alert System which allows access to real-time OONI data on the blocking of major social media platforms around the world**. This will be particularly useful to advocacy groups such as the #KeepItOn campaign, which makes use of OONI data to fight social media shutdowns worldwide. 

As part of this proposed project, we aim to develop a system that the public can refer to in order to learn when and where access to social media platforms is being restricted around the world based on empirical OONI data. This will entail **developing event detection capabilities in the OONI data processing pipeline** (with a focus on reducing the ratio of false positives) and exposing this information to end users.

**Comment by agrabeli** [comment] 2022-11-18 13:25
I have set a tentative timeline on zenhub which probably needs to be adjusted.

**Comment by hellais** [comment] 2023-08-09 12:35
This is a duplicate of https://github.com/ooni/backend/issues/629. I am closing this issue as the other one has more content in it.

**Closed by hellais** 2023-08-09 12:35 UTC
Labels: epic, funder/drl2022-2024
