### ISSUE TITLE
Next steps for Countly push to country plugin: fixes & QA

### ISSUE THREAD

**Issue by sarathms** [ooni/ooni.org#561] opened 2020-07-06 14:45 UTC
* [x] Remove duplicate entries in the country list dropdown
* [x] Verify that the Recipient count shown in Step 3,4 is generated correctly
* [x] QA (_in progress_; see https://github.com/ooni/ooni.org/issues/561#issuecomment-694418964)
* [x] Revert to es5 syntax in `frontend/**` files to enable production mode after compiling js files

**Comment by sarathms** [comment] 2020-09-10 09:23
The plugin now correctly calculates the target audience based on selections like country, platform, test/prod. It only takes into account users with messaging enabled.

**Comment by sarathms** [comment] 2020-09-10 22:09
![image-3.png](https://user-images.githubusercontent.com/700829/92814188-c2f68f00-f390-11ea-9d8b-44e67970c928.png)

![image-1.png](https://user-images.githubusercontent.com/700829/92814198-c853d980-f390-11ea-93ed-b1ecfe8e0586.png)

![image-2.png](https://user-images.githubusercontent.com/700829/92814207-cf7ae780-f390-11ea-916a-e45547180f26.png)

**Comment by bassosimone** [comment] 2020-09-14 06:47
This work has been implemented in:

* https://github.com/ooni/countly-push-to-country/commit/f52a7f08ff80e976f48918fa647ec15526551ebc
* https://github.com/ooni/countly-push-to-country/commit/3e86fc0e6423a164af21eab9965354b4514c33bc
* https://github.com/ooni/countly-push-to-country/commit/fd760f688c97f500f6ca162f08e9749ca7ae0b9d
* https://github.com/ooni/countly-push-to-country/commit/260b878e1439709e2292e25775cdb9b200ad9331

What is missing to close this issue is to perform QA.

**Comment by bassosimone** [comment] 2020-09-17 07:28
We're doing QA and specifically we're making sure that the work done here by @sarathms is working as intended for the now-ready-to-ship mobile apps as documented in https://github.com/ooni/probe/issues/1241.

**Comment by sarathms** [comment] 2020-09-17 18:29
QA steps would involve ensuring:

* users who enable notifications show up in the dashboard (country, platform etc. checks out)
* sending notifications to a single country goes to the user
* sending notifications to a combination of countries goes to those users
* sending notifications to all countries (no selections) goes to all users
* notifications do not reach users who had turned off notifications in the app

**Comment by bassosimone** [comment] 2020-09-17 18:33
Added also myself and @lorenzoPrimi. It seems we should be doing another round of QA here.

**Comment by bassosimone** [comment] 2020-09-24 13:15
Two days ago and yesterday we did run further testing. I'm going to move this issue to the Done column and ask @sarathms and @lorenzoPrimi for confirmation that we can really call this issue done.

**Comment by sarathms** [comment] 2020-09-24 15:04
Yes. the revert to es5 syntax was done in https://github.com/ooni/countly-push-to-country/commit/ea4f6901046998bcab85f1baf0d55e5d50b032ab

**Comment by bassosimone** [comment] 2020-09-24 15:55
Awesome to see that in the end the fix was small. GG @lorenzoPrimi @sarathms !

**Closed by bassosimone** 2020-09-24 15:55 UTC
Labels: effort/M, enhancement, priority/high
